// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartMovieCatalog.Infrastructure.Persistence;

#nullable disable

namespace SmartMovieCatalog.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SmartMovieCatalogDbContext))]
    partial class SmartMovieCatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartMovieCatalog.Domain.Movies.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Genres", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8130f6e7-0b55-4383-ab8a-2419a4a0bf84"),
                            Name = "Ação",
                            NormalizedName = "AÇÃO"
                        },
                        new
                        {
                            Id = new Guid("2ee73bcc-9d10-4881-8046-363802db5b61"),
                            Name = "Aventura",
                            NormalizedName = "AVENTURA"
                        },
                        new
                        {
                            Id = new Guid("9f2d4781-975e-4b86-887a-eae96a06e93e"),
                            Name = "Animação",
                            NormalizedName = "ANIMAÇÃO"
                        },
                        new
                        {
                            Id = new Guid("d0d2a285-d64c-4926-bb6e-bee246cb2066"),
                            Name = "Comédia",
                            NormalizedName = "COMÉDIA"
                        },
                        new
                        {
                            Id = new Guid("91ebc5ab-6a87-45fe-bcf4-e98d1f1c1c47"),
                            Name = "Crime",
                            NormalizedName = "CRIME"
                        },
                        new
                        {
                            Id = new Guid("cc60b818-3fe0-4a4c-904c-e6ff7c6bb14e"),
                            Name = "Documentário",
                            NormalizedName = "DOCUMENTÁRIO"
                        },
                        new
                        {
                            Id = new Guid("671a6527-8d6a-4773-8755-0702cce3859b"),
                            Name = "Drama",
                            NormalizedName = "DRAMA"
                        },
                        new
                        {
                            Id = new Guid("3dbe3e7c-b3a5-48d9-8539-c63f3263ca62"),
                            Name = "Família",
                            NormalizedName = "FAMÍLIA"
                        },
                        new
                        {
                            Id = new Guid("c5016fec-223b-4245-9619-4ebd9ed61616"),
                            Name = "Fantasia",
                            NormalizedName = "FANTASIA"
                        },
                        new
                        {
                            Id = new Guid("0bdb1338-15b8-4388-a600-4d6c1da3c9ac"),
                            Name = "História",
                            NormalizedName = "HISTÓRIA"
                        },
                        new
                        {
                            Id = new Guid("63186b3c-7ee8-4e27-b04e-93d38213b18f"),
                            Name = "Terror",
                            NormalizedName = "TERROR"
                        },
                        new
                        {
                            Id = new Guid("40d64d12-8dad-495d-9c8c-be79913a64a1"),
                            Name = "Música",
                            NormalizedName = "MÚSICA"
                        },
                        new
                        {
                            Id = new Guid("93685229-5cbb-4d6b-8583-320faff48c3a"),
                            Name = "Mistério",
                            NormalizedName = "MISTÉRIO"
                        },
                        new
                        {
                            Id = new Guid("b202ae42-19a0-4919-8531-4bd16535ba07"),
                            Name = "Romance",
                            NormalizedName = "ROMANCE"
                        },
                        new
                        {
                            Id = new Guid("65836d3b-9de2-4652-80d8-9f0a17da74e4"),
                            Name = "Ficção científica",
                            NormalizedName = "FICÇÃO CIENTÍFICA"
                        },
                        new
                        {
                            Id = new Guid("1b3b0c5c-b8a4-4a99-8ed3-c7829b1e04ba"),
                            Name = "Cinema TV",
                            NormalizedName = "CINEMA TV"
                        },
                        new
                        {
                            Id = new Guid("4a46f05d-370f-4a50-82e2-3d2160597c13"),
                            Name = "Thriller",
                            NormalizedName = "THRILLER"
                        },
                        new
                        {
                            Id = new Guid("ccfbe9c3-be3b-4a83-8d25-0788a19490e6"),
                            Name = "Guerra",
                            NormalizedName = "GUERRA"
                        },
                        new
                        {
                            Id = new Guid("ea89b466-98bd-4761-b883-a33f0effac99"),
                            Name = "Faroeste",
                            NormalizedName = "FAROESTE"
                        });
                });

            modelBuilder.Entity("SmartMovieCatalog.Domain.Movies.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AgeRating")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Director")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("integer");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("OriginalLanguage")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<string>("OriginalTitle")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("integer");

                    b.Property<string>("Synopsis")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.ToTable("Movies", (string)null);
                });

            modelBuilder.Entity("SmartMovieCatalog.Domain.Movies.MovieGenre", b =>
                {
                    b.Property<Guid>("MovieId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uuid");

                    b.HasKey("MovieId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("MovieGenres", (string)null);
                });

            modelBuilder.Entity("SmartMovieCatalog.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("MustChangePasswordOnFirstLogin")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("RemovedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SmartMovieCatalog.Domain.Movies.MovieGenre", b =>
                {
                    b.HasOne("SmartMovieCatalog.Domain.Movies.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartMovieCatalog.Domain.Movies.Movie", null)
                        .WithMany("Genres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("SmartMovieCatalog.Domain.Users.User", b =>
                {
                    b.OwnsMany("SmartMovieCatalog.Domain.Users.UserRole", "Roles", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("Role");

                            b1.HasKey("UserId", "Name");

                            b1.ToTable("UserRoles", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("SmartMovieCatalog.Domain.Movies.Movie", b =>
                {
                    b.Navigation("Genres");
                });
#pragma warning restore 612, 618
        }
    }
}
